Apitemplate
GBteammates/OnlineShopBackend pull request #14
Opened 2022-09-06 14:55 UTC by e4t4g

2022-09-07 09:47 UTC, sanyarise requested changes

2022-09-07 09:47 UTC, sanyarise commented on api/apionlineshop.yaml
> +        usreID:
Опечатка - "usreID", нужно поправить на "userID"

2022-09-07 09:47 UTC, sanyarise commented on api/apionlineshop.yaml
> +        cellphone:
В текущей реализации базы данных в таблице Users нет поля для телефона, нужно либо убрать этот параметр, либо добавить его в БД

2022-09-08 10:09 UTC, e4t4g commented on api/apionlineshop.yaml
> +        usreID:
Done

2022-09-08 10:10 UTC, e4t4g commented on api/apionlineshop.yaml
> +        cellphone:
Done. Temporarily removed

2022-09-10 05:56 UTC, sanyarise approved these changes

2022-09-10 05:57 UTC, sanyarise approved these changes

2022-09-10 08:08 UTC, merged